-- 1. Create new target spanner table
CREATE TABLE spanner (
    user_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    spanner_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_spanner PRIMARY KEY (user_id, channel_id)
);

CREATE INDEX idx_spanner_user_id ON spanner(user_id);
CREATE INDEX idx_spanner_channel_id ON spanner(channel_id);

-- 2. Migrate data: Copy from old 'spanners' table to new 'spanner' table
-- Default timestamps to NOW() for old existing records which previously did not have them

INSERT INTO spanner (user_id, channel_id, spanner_count)
SELECT user_id, channel_id, spanner_count
FROM spanners;

-- 3. Retire the old 'spanners' table by renaming it
ALTER TABLE spanners RENAME TO spanners_old;

-- 4. Create the audit_event table for tracking events
CREATE TABLE audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT NOT NULL,
    user_id BIGINT,  -- Nullable: some events may not be user-specific
    event_type VARCHAR(50) NOT NULL,
    event_data JSONB,  -- Type-specific fields stored as JSON
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for common query patterns
CREATE INDEX idx_audit_event_channel_id ON audit_event(channel_id);
CREATE INDEX idx_audit_event_user_id ON audit_event(user_id) WHERE user_id IS NOT NULL;
CREATE INDEX idx_audit_event_type ON audit_event(event_type);
CREATE INDEX idx_audit_event_occurred_at ON audit_event(occurred_at);
CREATE INDEX idx_audit_event_channel_occurred ON audit_event(channel_id, occurred_at DESC);
CREATE INDEX idx_audit_event_data ON audit_event USING GIN (event_data);

COMMENT ON TABLE spanner IS 'Tracks spanner counts for users per channel';
COMMENT ON TABLE audit_event IS 'Audit trail of all events that occur in channels';
