CREATE TABLE ten_man_poll (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id           BIGINT NOT NULL,
    created_by_user_id   BIGINT NOT NULL,
    discord_message_id   BIGINT,
    status               VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uq_ten_man_poll_active_channel ON ten_man_poll (channel_id) WHERE status = 'ACTIVE';

CREATE TABLE ten_man_date_option (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id      BIGINT NOT NULL REFERENCES ten_man_poll(id) ON DELETE CASCADE,
    option_date  DATE NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uq_ten_man_date_option_poll_date ON ten_man_date_option (poll_id, option_date);

CREATE TABLE ten_man_signup (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_option_id BIGINT NOT NULL REFERENCES ten_man_date_option(id) ON DELETE CASCADE,
    user_id        BIGINT NOT NULL,
    signed_up_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uq_ten_man_signup_option_user ON ten_man_signup (date_option_id, user_id);
